//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebShop.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class Item : EntityBase
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Item()
        {
            this.TrOrders = new HashSet<TrOrder>();
        }
    
        public int IdItem { get; set; }
        public string Code { get; set; }
        public string Description { get; set; }
        public int IdType { get; set; }
        public System.DateTime Vs_date { get; set; }
    
        public virtual Type Type { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TrOrder> TrOrders { get; set; }
    }
}
